<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="../../style.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="icon" href="https://trello-attachments.s3.amazonaws.com/5f5aa6890a57b727311dcc05/542x306/27d4ee40c39bde0a47e3ff66b5326607/image.png">


    <title>INSERT</title>
</head>
<body>
    
</body>
<footer class="footer">
    <a class="active" href="#" target="_self">INSERT |</a>
    <a href="../update/PUT.php" target="_self">UPDATE |</a>
    <a href="../delete/DEL.php" target="_self">DELETE |</a>
    <a href="../read/GET.php" target="_self">READ |</a>
</footer>
</html>